version: "0.5"

# TODO: Once nixpkgs process-compose is updated to include the --detached flag,
# update the onBoot command to use: process-compose up --detached -t=false
# This would be cleaner than the current setsid workaround.
# If this becomes an issue, we could instruct the AI to download the binary
# directly from: https://github.com/F1bonacc1/process-compose/releases/latest

processes:
  lexe-sidecar:
    # Use ./.local/bin instead of ~/.local/bin because in Replit
    # the install script places binaries in the project directory
    command: "./.local/bin/lexe-sidecar"
    # Set to false because lexe-sidecar runs as a foreground process,
    # not a self-daemonizing background process
    is_daemon: false
    availability:
      restart: "always"
    readiness_probe:
      http_get:
        host: "localhost"
        port: 5393
        path: "/v2/health"
      initial_delay_seconds: 2
      period_seconds: 10
      timeout_seconds: 5
      failure_threshold: 3
    shutdown:
      signal: 15  # SIGTERM
      timeout_seconds: 10
    log_configuration:
      rotation:
        max_size_mb: 10
        max_age_days: 3
